-- 1. Tabela TUTOR
CREATE TABLE TUTOR (
    ID_Tutor INT PRIMARY KEY AUTO_INCREMENT, -- PK
    Nome VARCHAR(100) NOT NULL,
    Telefone VARCHAR(15) NOT NULL,
    Endereco VARCHAR(255)
);

-- 2. Tabela VETERINARIO
CREATE TABLE VETERINARIO (
    ID_Vet INT PRIMARY KEY AUTO_INCREMENT, -- PK
    Nome VARCHAR(100) NOT NULL,
    CRMV VARCHAR(20) UNIQUE NOT NULL,
    Especialidade VARCHAR(50)
);

-- 3. Tabela ANIMAL
CREATE TABLE ANIMAL (
    ID_Animal INT PRIMARY KEY AUTO_INCREMENT, -- PK
    Nome VARCHAR(100) NOT NULL,
    Raca VARCHAR(50),
    Data_Nascimento DATE,
    ID_Tutor INT NOT NULL, -- FK
    FOREIGN KEY (ID_Tutor) REFERENCES TUTOR(ID_Tutor)
);

-- 4. Tabela AGENDAMENTO
CREATE TABLE AGENDAMENTO (
    ID_Agendamento INT PRIMARY KEY AUTO_INCREMENT, -- PK
    Data DATE NOT NULL,
    Hora TIME NOT NULL,
    Status VARCHAR(20) DEFAULT 'Pendente',
    ID_Animal INT NOT NULL, -- FK
    ID_Vet INT NOT NULL,     -- FK
    FOREIGN KEY (ID_Animal) REFERENCES ANIMAL(ID_Animal),
    FOREIGN KEY (ID_Vet) REFERENCES VETERINARIO(ID_Vet)
);

-- 5. Tabela ATENDIMENTO
CREATE TABLE ATENDIMENTO (
    ID_Atendimento INT PRIMARY KEY AUTO_INCREMENT, -- PK
    Data DATE NOT NULL,
    Diagnostico TEXT,
    Procedimento TEXT,
    ID_Animal INT NOT NULL, -- FK
    ID_Vet INT NOT NULL,     -- FK
    ID_Agendamento INT UNIQUE NOT NULL, -- FK e UNIQUE (garante 1:1 com AGENDAMENTO)
    FOREIGN KEY (ID_Animal) REFERENCES ANIMAL(ID_Animal),
    FOREIGN KEY (ID_Vet) REFERENCES VETERINARIO(ID_Vet),
    FOREIGN KEY (ID_Agendamento) REFERENCES AGENDAMENTO(ID_Agendamento)
);

-- 6. Tabela USUARIO_SISTEMA
CREATE TABLE USUARIO_SISTEMA (
    ID_Usuario INT PRIMARY KEY AUTO_INCREMENT, -- PK
    Nome VARCHAR(100) NOT NULL,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Funcao VARCHAR(50) NOT NULL
);